export default [
  { path: '/',                        component: require('./pages/HomePage.vue') },
  { path: '/catalog',                 redirect: 'catalog/products' },
  { path: '/catalog/products',        component: require('./pages/ProductPage.vue') },
  { path: '/catalog/categories',      component: require('./pages/TodoPage.vue') },
  { path: '/catalog/media',           component: require('./pages/TodoPage.vue') },
  { path: '/orders',                  redirect: 'orders/claims' },
  { path: '/orders/claims',           component: require('./pages/TodoPage.vue') },
  { path: '/orders/completed',        component: require('./pages/TodoPage.vue') },
  { path: '/orders/returned',         component: require('./pages/TodoPage.vue') },
  { path: '/orders/archived',          component: require('./pages/TodoPage.vue') },
  { path: '/statistics',              redirect: 'statistics/sales' },
  { path: '/statistics/sales',        component: require('./pages/TodoPage.vue') },
  { path: '/statistics/reports',      component: require('./pages/TodoPage.vue') },
  { path: '/statistics/traffic',      component: require('./pages/TodoPage.vue') },
  { path: '/statistics/views',        component: require('./pages/TodoPage.vue') },
  { path: '/customers',               redirect: 'customers/messages' },
  { path: '/customers/messages',      component: require('./pages/TodoPage.vue') },
  { path: '/customers/users',         component: require('./pages/TodoPage.vue') },
  { path: '/customers/newsletter',    component: require('./pages/TodoPage.vue') },
  { path: '/customers/carts',         component: require('./pages/TodoPage.vue') },
  { path: '/settings',                redirect: 'settings/admins' },
  { path: '/settings/admins',         component: require('./pages/TodoPage.vue') },
  { path: '*',                        redirect: '/'}
]